// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: admin_profiles.proto

package __

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAdminProfileOut_CreateAdminProfileError int32

const (
	CreateAdminProfileOut_NO_ERROR               CreateAdminProfileOut_CreateAdminProfileError = 0
	CreateAdminProfileOut_ERROR_CREATING_PROFILE CreateAdminProfileOut_CreateAdminProfileError = 1
)

// Enum value maps for CreateAdminProfileOut_CreateAdminProfileError.
var (
	CreateAdminProfileOut_CreateAdminProfileError_name = map[int32]string{
		0: "NO_ERROR",
		1: "ERROR_CREATING_PROFILE",
	}
	CreateAdminProfileOut_CreateAdminProfileError_value = map[string]int32{
		"NO_ERROR":               0,
		"ERROR_CREATING_PROFILE": 1,
	}
)

func (x CreateAdminProfileOut_CreateAdminProfileError) Enum() *CreateAdminProfileOut_CreateAdminProfileError {
	p := new(CreateAdminProfileOut_CreateAdminProfileError)
	*p = x
	return p
}

func (x CreateAdminProfileOut_CreateAdminProfileError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateAdminProfileOut_CreateAdminProfileError) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_profiles_proto_enumTypes[0].Descriptor()
}

func (CreateAdminProfileOut_CreateAdminProfileError) Type() protoreflect.EnumType {
	return &file_admin_profiles_proto_enumTypes[0]
}

func (x CreateAdminProfileOut_CreateAdminProfileError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateAdminProfileOut_CreateAdminProfileError.Descriptor instead.
func (CreateAdminProfileOut_CreateAdminProfileError) EnumDescriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{2, 0}
}

type LoginAdminProfileInOut_LoginAdminProfileError int32

const (
	LoginAdminProfileInOut_NO_ERROR            LoginAdminProfileInOut_LoginAdminProfileError = 0
	LoginAdminProfileInOut_ERROR_LOGIN_PROFILE LoginAdminProfileInOut_LoginAdminProfileError = 1
)

// Enum value maps for LoginAdminProfileInOut_LoginAdminProfileError.
var (
	LoginAdminProfileInOut_LoginAdminProfileError_name = map[int32]string{
		0: "NO_ERROR",
		1: "ERROR_LOGIN_PROFILE",
	}
	LoginAdminProfileInOut_LoginAdminProfileError_value = map[string]int32{
		"NO_ERROR":            0,
		"ERROR_LOGIN_PROFILE": 1,
	}
)

func (x LoginAdminProfileInOut_LoginAdminProfileError) Enum() *LoginAdminProfileInOut_LoginAdminProfileError {
	p := new(LoginAdminProfileInOut_LoginAdminProfileError)
	*p = x
	return p
}

func (x LoginAdminProfileInOut_LoginAdminProfileError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginAdminProfileInOut_LoginAdminProfileError) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_profiles_proto_enumTypes[1].Descriptor()
}

func (LoginAdminProfileInOut_LoginAdminProfileError) Type() protoreflect.EnumType {
	return &file_admin_profiles_proto_enumTypes[1]
}

func (x LoginAdminProfileInOut_LoginAdminProfileError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginAdminProfileInOut_LoginAdminProfileError.Descriptor instead.
func (LoginAdminProfileInOut_LoginAdminProfileError) EnumDescriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{4, 0}
}

type LogoutAdminProfileInOut_LogoutAdminProfileError int32

const (
	LogoutAdminProfileInOut_NO_ERROR             LogoutAdminProfileInOut_LogoutAdminProfileError = 0
	LogoutAdminProfileInOut_ERROR_LOGOUT_PROFILE LogoutAdminProfileInOut_LogoutAdminProfileError = 1
)

// Enum value maps for LogoutAdminProfileInOut_LogoutAdminProfileError.
var (
	LogoutAdminProfileInOut_LogoutAdminProfileError_name = map[int32]string{
		0: "NO_ERROR",
		1: "ERROR_LOGOUT_PROFILE",
	}
	LogoutAdminProfileInOut_LogoutAdminProfileError_value = map[string]int32{
		"NO_ERROR":             0,
		"ERROR_LOGOUT_PROFILE": 1,
	}
)

func (x LogoutAdminProfileInOut_LogoutAdminProfileError) Enum() *LogoutAdminProfileInOut_LogoutAdminProfileError {
	p := new(LogoutAdminProfileInOut_LogoutAdminProfileError)
	*p = x
	return p
}

func (x LogoutAdminProfileInOut_LogoutAdminProfileError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogoutAdminProfileInOut_LogoutAdminProfileError) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_profiles_proto_enumTypes[2].Descriptor()
}

func (LogoutAdminProfileInOut_LogoutAdminProfileError) Type() protoreflect.EnumType {
	return &file_admin_profiles_proto_enumTypes[2]
}

func (x LogoutAdminProfileInOut_LogoutAdminProfileError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogoutAdminProfileInOut_LogoutAdminProfileError.Descriptor instead.
func (LogoutAdminProfileInOut_LogoutAdminProfileError) EnumDescriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{6, 0}
}

type CreateAdminProfileIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *AdminProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *CreateAdminProfileIn) Reset() {
	*x = CreateAdminProfileIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_profiles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdminProfileIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminProfileIn) ProtoMessage() {}

func (x *CreateAdminProfileIn) ProtoReflect() protoreflect.Message {
	mi := &file_admin_profiles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminProfileIn.ProtoReflect.Descriptor instead.
func (*CreateAdminProfileIn) Descriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAdminProfileIn) GetProfile() *AdminProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type AdminProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AdminProfile) Reset() {
	*x = AdminProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_profiles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfile) ProtoMessage() {}

func (x *AdminProfile) ProtoReflect() protoreflect.Message {
	mi := &file_admin_profiles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProfile.ProtoReflect.Descriptor instead.
func (*AdminProfile) Descriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *AdminProfile) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AdminProfile) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateAdminProfileOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   CreateAdminProfileOut_CreateAdminProfileError `protobuf:"varint,1,opt,name=error,proto3,enum=admin_profiles.CreateAdminProfileOut_CreateAdminProfileError" json:"error,omitempty"`
	Session string                                        `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *CreateAdminProfileOut) Reset() {
	*x = CreateAdminProfileOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_profiles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdminProfileOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminProfileOut) ProtoMessage() {}

func (x *CreateAdminProfileOut) ProtoReflect() protoreflect.Message {
	mi := &file_admin_profiles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminProfileOut.ProtoReflect.Descriptor instead.
func (*CreateAdminProfileOut) Descriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdminProfileOut) GetError() CreateAdminProfileOut_CreateAdminProfileError {
	if x != nil {
		return x.Error
	}
	return CreateAdminProfileOut_NO_ERROR
}

func (x *CreateAdminProfileOut) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type LoginAdminProfileIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *AdminProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *LoginAdminProfileIn) Reset() {
	*x = LoginAdminProfileIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_profiles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginAdminProfileIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminProfileIn) ProtoMessage() {}

func (x *LoginAdminProfileIn) ProtoReflect() protoreflect.Message {
	mi := &file_admin_profiles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminProfileIn.ProtoReflect.Descriptor instead.
func (*LoginAdminProfileIn) Descriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *LoginAdminProfileIn) GetProfile() *AdminProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type LoginAdminProfileInOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string                                        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Error   LoginAdminProfileInOut_LoginAdminProfileError `protobuf:"varint,2,opt,name=error,proto3,enum=admin_profiles.LoginAdminProfileInOut_LoginAdminProfileError" json:"error,omitempty"`
}

func (x *LoginAdminProfileInOut) Reset() {
	*x = LoginAdminProfileInOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_profiles_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginAdminProfileInOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminProfileInOut) ProtoMessage() {}

func (x *LoginAdminProfileInOut) ProtoReflect() protoreflect.Message {
	mi := &file_admin_profiles_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminProfileInOut.ProtoReflect.Descriptor instead.
func (*LoginAdminProfileInOut) Descriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{4}
}

func (x *LoginAdminProfileInOut) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *LoginAdminProfileInOut) GetError() LoginAdminProfileInOut_LoginAdminProfileError {
	if x != nil {
		return x.Error
	}
	return LoginAdminProfileInOut_NO_ERROR
}

type LogoutAdminProfileIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *AdminProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *LogoutAdminProfileIn) Reset() {
	*x = LogoutAdminProfileIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_profiles_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutAdminProfileIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAdminProfileIn) ProtoMessage() {}

func (x *LogoutAdminProfileIn) ProtoReflect() protoreflect.Message {
	mi := &file_admin_profiles_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAdminProfileIn.ProtoReflect.Descriptor instead.
func (*LogoutAdminProfileIn) Descriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutAdminProfileIn) GetProfile() *AdminProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type LogoutAdminProfileInOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *AdminProfile                                   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Error   LogoutAdminProfileInOut_LogoutAdminProfileError `protobuf:"varint,2,opt,name=error,proto3,enum=admin_profiles.LogoutAdminProfileInOut_LogoutAdminProfileError" json:"error,omitempty"`
}

func (x *LogoutAdminProfileInOut) Reset() {
	*x = LogoutAdminProfileInOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_profiles_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutAdminProfileInOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAdminProfileInOut) ProtoMessage() {}

func (x *LogoutAdminProfileInOut) ProtoReflect() protoreflect.Message {
	mi := &file_admin_profiles_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAdminProfileInOut.ProtoReflect.Descriptor instead.
func (*LogoutAdminProfileInOut) Descriptor() ([]byte, []int) {
	return file_admin_profiles_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutAdminProfileInOut) GetProfile() *AdminProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *LogoutAdminProfileInOut) GetError() LogoutAdminProfileInOut_LogoutAdminProfileError {
	if x != nil {
		return x.Error
	}
	return LogoutAdminProfileInOut_NO_ERROR
}

var File_admin_profiles_proto protoreflect.FileDescriptor

var file_admin_profiles_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x12, 0x36,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xcb, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4f,
	0x75, 0x74, 0x12, 0x53, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x3d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x43, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x08,
	0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x52, 0x4f,
	0x46, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x22, 0x4d, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x12, 0x36, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x4f, 0x75, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x53, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x4f, 0x75,
	0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x3f, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x01,
	0x22, 0x4e, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0xeb, 0x01, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x4f, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x55, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x3f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x4f, 0x75, 0x74, 0x2e, 0x4c, 0x6f, 0x67,
	0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x41, 0x0a, 0x17, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4c, 0x4f,
	0x47, 0x4f, 0x55, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x32, 0xbd,
	0x02, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x63, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x24, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x1a, 0x25, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x23, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x1a,
	0x26, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x12, 0x4c, 0x6f, 0x67,
	0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x23, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x1a, 0x26, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x03,
	0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_profiles_proto_rawDescOnce sync.Once
	file_admin_profiles_proto_rawDescData = file_admin_profiles_proto_rawDesc
)

func file_admin_profiles_proto_rawDescGZIP() []byte {
	file_admin_profiles_proto_rawDescOnce.Do(func() {
		file_admin_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_profiles_proto_rawDescData)
	})
	return file_admin_profiles_proto_rawDescData
}

var file_admin_profiles_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_admin_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_admin_profiles_proto_goTypes = []interface{}{
	(CreateAdminProfileOut_CreateAdminProfileError)(0),   // 0: admin_profiles.CreateAdminProfileOut.CreateAdminProfileError
	(LoginAdminProfileInOut_LoginAdminProfileError)(0),   // 1: admin_profiles.LoginAdminProfileInOut.LoginAdminProfileError
	(LogoutAdminProfileInOut_LogoutAdminProfileError)(0), // 2: admin_profiles.LogoutAdminProfileInOut.LogoutAdminProfileError
	(*CreateAdminProfileIn)(nil),                         // 3: admin_profiles.CreateAdminProfileIn
	(*AdminProfile)(nil),                                 // 4: admin_profiles.AdminProfile
	(*CreateAdminProfileOut)(nil),                        // 5: admin_profiles.CreateAdminProfileOut
	(*LoginAdminProfileIn)(nil),                          // 6: admin_profiles.LoginAdminProfileIn
	(*LoginAdminProfileInOut)(nil),                       // 7: admin_profiles.LoginAdminProfileInOut
	(*LogoutAdminProfileIn)(nil),                         // 8: admin_profiles.LogoutAdminProfileIn
	(*LogoutAdminProfileInOut)(nil),                      // 9: admin_profiles.LogoutAdminProfileInOut
}
var file_admin_profiles_proto_depIdxs = []int32{
	4,  // 0: admin_profiles.CreateAdminProfileIn.profile:type_name -> admin_profiles.AdminProfile
	0,  // 1: admin_profiles.CreateAdminProfileOut.error:type_name -> admin_profiles.CreateAdminProfileOut.CreateAdminProfileError
	4,  // 2: admin_profiles.LoginAdminProfileIn.profile:type_name -> admin_profiles.AdminProfile
	1,  // 3: admin_profiles.LoginAdminProfileInOut.error:type_name -> admin_profiles.LoginAdminProfileInOut.LoginAdminProfileError
	4,  // 4: admin_profiles.LogoutAdminProfileIn.profile:type_name -> admin_profiles.AdminProfile
	4,  // 5: admin_profiles.LogoutAdminProfileInOut.profile:type_name -> admin_profiles.AdminProfile
	2,  // 6: admin_profiles.LogoutAdminProfileInOut.error:type_name -> admin_profiles.LogoutAdminProfileInOut.LogoutAdminProfileError
	3,  // 7: admin_profiles.AdminProfiles.CreateAdminProfile:input_type -> admin_profiles.CreateAdminProfileIn
	6,  // 8: admin_profiles.AdminProfiles.LoginAdminProfile:input_type -> admin_profiles.LoginAdminProfileIn
	6,  // 9: admin_profiles.AdminProfiles.LogoutAdminProfile:input_type -> admin_profiles.LoginAdminProfileIn
	5,  // 10: admin_profiles.AdminProfiles.CreateAdminProfile:output_type -> admin_profiles.CreateAdminProfileOut
	7,  // 11: admin_profiles.AdminProfiles.LoginAdminProfile:output_type -> admin_profiles.LoginAdminProfileInOut
	7,  // 12: admin_profiles.AdminProfiles.LogoutAdminProfile:output_type -> admin_profiles.LoginAdminProfileInOut
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_profiles_proto_init() }
func file_admin_profiles_proto_init() {
	if File_admin_profiles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_profiles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdminProfileIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_profiles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_profiles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdminProfileOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_profiles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginAdminProfileIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_profiles_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginAdminProfileInOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_profiles_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutAdminProfileIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_profiles_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutAdminProfileInOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_profiles_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_profiles_proto_goTypes,
		DependencyIndexes: file_admin_profiles_proto_depIdxs,
		EnumInfos:         file_admin_profiles_proto_enumTypes,
		MessageInfos:      file_admin_profiles_proto_msgTypes,
	}.Build()
	File_admin_profiles_proto = out.File
	file_admin_profiles_proto_rawDesc = nil
	file_admin_profiles_proto_goTypes = nil
	file_admin_profiles_proto_depIdxs = nil
}
